[package]
name = "f1-led-circuit-nearest_neighbor"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.203"
nabo = "0.3.0"